"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variable loading
# Use django-environ - explicitly point to .env in same directory as settings.py
try:
    import environ
except ImportError as e:
    print(f"[SETTINGS ERROR] Failed to import environ module")
    print(f"[SETTINGS ERROR] Python executable: {sys.executable}")
    print(f"[SETTINGS ERROR] Python path: {sys.path[:3]}")
    print(f"[SETTINGS ERROR] Import error: {e}")
    print(f"[SETTINGS ERROR] Please install django-environ: pip install django-environ")
    raise

# .env file should be in backend/ directory (backend/.env)
env_file = BASE_DIR / '.env'
env = environ.Env(
    # Set casting and default values
    DEBUG=(bool, False),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_PORT=(int, 587),
)

# Read .env file from core/ directory
if env_file.exists():
    env.read_env(str(env_file))
    print(f"[SETTINGS] Loading .env from: {env_file}")
else:
    print(f"[SETTINGS] WARNING: .env file not found at {env_file}")

# Helper function for compatibility
def config(key, default=None, cast=None):
    """Helper function to read env vars with optional casting"""
    try:
        if cast is not None:
            return env(key, cast=cast, default=default)
        return env(key, default=default)
    except Exception:
        return default

def Csv(value, cast=None):
    """Helper function for comma-separated values"""
    if value is None:
        return []
    return [v.strip() for v in value.split(',') if v.strip()]


def get_env_bool(key, default=False):
    """Get boolean environment variable"""
    return env(key, cast=bool, default=default)


def get_env_list(key, default=None):
    """Get list environment variable (comma-separated)
    
    Returns a list, ensuring Django's ALLOWED_HOSTS requirement is met.
    Always returns a list (never None, tuple, or other types).
    """
    # Normalize default to a list
    if default is None:
        default_list = []
    elif isinstance(default, (list, tuple)):
        default_list = list(default)
    else:
        default_list = [str(default)]
    
    # Ensure default_list is a list
    if not isinstance(default_list, list):
        default_list = []
    
    # Helper function to ensure result is always a list
    def ensure_list(value, fallback_default):
        """Ensure value is a list, otherwise return fallback_default"""
        if isinstance(value, list):
            return value
        elif isinstance(value, tuple):
            return list(value)
        elif value is None:
            return fallback_default.copy() if fallback_default else []
        else:
            return fallback_default.copy() if fallback_default else []
    
    # Use django-environ to read comma-separated values
    try:
        # Convert default list to comma-separated string
        if default_list:
            default_str = ','.join(str(v) for v in default_list)
        else:
            default_str = ''
        
        # Get value from environment as string
        try:
            raw_str = env(key, default=default_str)
            # If empty, use default
            if not raw_str or raw_str.strip() == '':
                return ensure_list(None, default_list)
            # Parse comma-separated string manually
            parsed_list = [v.strip() for v in str(raw_str).split(',') if v.strip()]
            # If parsing results in empty list, use default
            if not parsed_list:
                return ensure_list(None, default_list)
        except Exception:
            # If env fails, use default
            return ensure_list(None, default_list)
        
        # Filter out empty strings and None values
        filtered_list = [str(v).strip() for v in parsed_list if v is not None and str(v).strip()]
        
        # If filtered list is empty and we have a default, return default
        if not filtered_list and default_list:
            return ensure_list(default_list.copy(), default_list)
        
        # Return filtered list (ensure it's a list)
        return ensure_list(filtered_list, default_list)
        
    except Exception:
        # On any exception, return default as a list
        return ensure_list(None, default_list)
    
    # Fallback (should not reach here, but just in case)
    try:
        value = env(key, default='')
        if not value or value == '':
            return ensure_list(None, default_list)
        
        # Split comma-separated values
        result = [v.strip() for v in str(value).split(',') if v.strip()]
        if not result:
            return ensure_list(None, default_list)
        return ensure_list(result, default_list)
    except Exception:
        # On any error, return default as a list
        return ensure_list(None, default_list)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment variable - REQUIRED in production
SECRET_KEY = config('SECRET_KEY', default='django-insecure-lc*ju4=46*vlq62ladn2_l1tb)h%#roituyojqs#czz^j&^tof')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG should be False in production - set via environment variable
DEBUG = get_env_bool('DEBUG', default=True)

# ALLOWED_HOSTS - must be set in production via environment variable
ALLOWED_HOSTS = get_env_list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Warn if using insecure defaults
if DEBUG and SECRET_KEY.startswith('django-insecure-'):
    import warnings
    warnings.warn(
        'WARNING: Using insecure SECRET_KEY. Set SECRET_KEY environment variable in production!',
        UserWarning
    )

APPEND_SLASH = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'django_extensions',
    'actstream',
    'auditlog',
    'drf_spectacular',
    'users',
    'emails',
    'dns',
    'site_settings.apps.SettingsConfig',
    'audit_reports',
]

# Conditionally add anymail if available
try:
    import anymail
    INSTALLED_APPS.insert(INSTALLED_APPS.index('rest_framework'), 'anymail')
except ImportError:
    pass

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Rate limiting middleware (if django-ratelimit is installed)
    # Note: Rate limiting is applied via decorators in views
    # Custom middleware for logging and monitoring
    'core.middleware.RequestResponseLoggingMiddleware',
    'core.middleware.PerformanceMonitoringMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],  # Add core templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Load database credentials from environment variables
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='pagerodeo'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='127.0.0.1'),  # Use 127.0.0.1 instead of localhost to force IPv4
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Email Configuration
# Check if anymail is available, otherwise fall back to SMTP
try:
    import anymail
    # Default to Amazon SES via django-anymail if EMAIL_BACKEND not explicitly set
    EMAIL_BACKEND = env('EMAIL_BACKEND', default='anymail.backends.amazon_ses.EmailBackend')
except ImportError:
    # Fallback to SMTP if anymail is not installed
    EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')

# SMTP configuration
# Use env() to read from .env file
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env('EMAIL_PORT', cast=int, default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', cast=bool, default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# Debug logging
if DEBUG:
    print(f"[SETTINGS] EMAIL_HOST_USER loaded: '{EMAIL_HOST_USER}' (type: {type(EMAIL_HOST_USER).__name__}, empty: {not EMAIL_HOST_USER})")

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

if DEBUG:
    print(f"[SETTINGS] DEFAULT_FROM_EMAIL loaded: '{DEFAULT_FROM_EMAIL}' (type: {type(DEFAULT_FROM_EMAIL).__name__}, empty: {not DEFAULT_FROM_EMAIL})")
SERVER_EMAIL = env('SERVER_EMAIL', default=env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER))

# anymail (Amazon SES) configuration
# If using Amazon SES with API, set AWS creds and region in environment
try:
    import anymail
    ANYMAIL = {
        "AMAZON_SES_CLIENT_PARAMS": {
            # boto3 will also read standard AWS env vars:
            # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN
            "region_name": config('AWS_REGION', default=config('AWS_DEFAULT_REGION', default='us-east-1')),
        }
    }
except ImportError:
    ANYMAIL = {}

# Email settings common
EMAIL_TIMEOUT = 30
EMAIL_USE_SSL = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directory where collectstatic will gather all static files

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Token Configuration
# Default was 5 minutes, now set to 30 minutes for better user experience
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Changed from default 5 minutes to 30 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Default: 1 day
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'PageRodeo API',
    'DESCRIPTION': 'User Management and Performance Testing API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# PostHog Analytics Configuration
# Import PostHog config (will be None if not configured)
try:
    from core.posthog_config import posthog_client, capture_event, identify_user
except ImportError:
    posthog_client = None
    capture_event = lambda *args, **kwargs: None
    identify_user = lambda *args, **kwargs: None

# Centralized Logging Configuration
try:
    from core.logging_config import LOGGING
except ImportError:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    }

# Security Configuration
# Import security settings from security_config.py
try:
    from core.security_config import (
        SECURE_SSL_REDIRECT,
        SECURE_HSTS_SECONDS,
        SECURE_HSTS_INCLUDE_SUBDOMAINS,
        SECURE_HSTS_PRELOAD,
        SECURE_CONTENT_TYPE_NOSNIFF,
        SECURE_BROWSER_XSS_FILTER,
        X_FRAME_OPTIONS,
        SECURE_REFERRER_POLICY,
        SECURE_PROXY_SSL_HEADER,
        SESSION_COOKIE_SECURE,
        SESSION_COOKIE_HTTPONLY,
        SESSION_COOKIE_SAMESITE,
        CSRF_COOKIE_SECURE,
        CSRF_COOKIE_HTTPONLY,
        CSRF_COOKIE_SAMESITE,
        RATE_LIMIT_ENABLE,
        RATE_LIMIT_PER_MINUTE,
        RATE_LIMIT_PER_HOUR,
    )
    
    # HTTPS Enforcement
    SECURE_SSL_REDIRECT = SECURE_SSL_REDIRECT
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = SECURE_HSTS_SECONDS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_INCLUDE_SUBDOMAINS
    SECURE_HSTS_PRELOAD = SECURE_HSTS_PRELOAD
    
    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = SECURE_CONTENT_TYPE_NOSNIFF
    SECURE_BROWSER_XSS_FILTER = SECURE_BROWSER_XSS_FILTER
    X_FRAME_OPTIONS = X_FRAME_OPTIONS
    SECURE_REFERRER_POLICY = SECURE_REFERRER_POLICY
    
    # Proxy SSL Header (if behind reverse proxy)
    # Must be a tuple of (header_name, header_value) for Django
    if SECURE_PROXY_SSL_HEADER:
        # Convert to tuple if it's a list or Csv object
        if isinstance(SECURE_PROXY_SSL_HEADER, (list, tuple)) or hasattr(SECURE_PROXY_SSL_HEADER, '__iter__'):
            if not isinstance(SECURE_PROXY_SSL_HEADER, str):
                SECURE_PROXY_SSL_HEADER = tuple(SECURE_PROXY_SSL_HEADER)
                # Ensure it has exactly 2 elements
                if len(SECURE_PROXY_SSL_HEADER) != 2:
                    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Secure Cookies
    SESSION_COOKIE_SECURE = SESSION_COOKIE_SECURE
    SESSION_COOKIE_HTTPONLY = SESSION_COOKIE_HTTPONLY
    SESSION_COOKIE_SAMESITE = SESSION_COOKIE_SAMESITE
    CSRF_COOKIE_SECURE = CSRF_COOKIE_SECURE
    CSRF_COOKIE_HTTPONLY = CSRF_COOKIE_HTTPONLY
    CSRF_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE
    
    # Rate Limiting Settings
    RATE_LIMIT_ENABLE = RATE_LIMIT_ENABLE
    RATE_LIMIT_PER_MINUTE = RATE_LIMIT_PER_MINUTE
    RATE_LIMIT_PER_HOUR = RATE_LIMIT_PER_HOUR
    
except ImportError:
    # Fallback security settings if security_config.py is not available
    # These are production-safe defaults
    SECURE_SSL_REDIRECT = not DEBUG
    SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
    SECURE_HSTS_PRELOAD = not DEBUG
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SESSION_COOKIE_SECURE = not DEBUG
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = not DEBUG
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    RATE_LIMIT_ENABLE = True
    RATE_LIMIT_PER_MINUTE = 60
    RATE_LIMIT_PER_HOUR = 1000

# Content Security Policy (CSP)
# Note: django-csp is not installed by default
# To enable CSP, install: pip install django-csp
# Then add 'csp' to INSTALLED_APPS and 'csp.middleware.CSPMiddleware' to MIDDLEWARE
try:
    import csp
    # CSP is available
    CSP_ENABLED = True
except ImportError:
    CSP_ENABLED = False
    # CSP settings (will be ignored if django-csp is not installed)
    CSP_DEFAULT_SRC = ["'self'"]
    CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'", "'unsafe-eval'"]
    CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]
    CSP_IMG_SRC = ["'self'", 'data:', 'https:']
    CSP_FONT_SRC = ["'self'", 'data:']
    CSP_CONNECT_SRC = ["'self'"]
    CSP_FRAME_SRC = ["'self'"]