# Generated by Django 5.2.6 on 2026-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='allowed_schemas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='connection_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='connection_timeout',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='connection_type',
            field=models.CharField(choices=[('direct', 'Direct TCP/IP'), ('tls', 'TLS/SSL'), ('ssh_tunnel', 'SSH Tunnel'), ('ssh_jump', 'SSH Jump Host'), ('iam', 'Cloud IAM'), ('proxy', 'Database Proxy'), ('agent', 'Agent-Based')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='last_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='max_connections',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='query_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='query_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssl_ca_cert',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssl_client_cert',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssl_client_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssl_mode',
            field=models.CharField(choices=[('disable', 'Disable'), ('allow', 'Allow'), ('prefer', 'Prefer'), ('require', 'Require'), ('verify-ca', 'Verify CA'), ('verify-full', 'Verify Full')], default='prefer', max_length=20),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='engine',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL / MariaDB'), ('sqlite', 'SQLite'), ('mssql', 'SQL Server'), ('oracle', 'Oracle'), ('mongodb', 'MongoDB'), ('redis', 'Redis')], max_length=20),
        ),
    ]
